// Generated by `sflock pull --agent geo` from GEOAnswers.json. Do not edit — re-pull.

export interface GEOAnswers {
  Answer?: string;
  /**
   * ISO 8601 date or date-time
   */
  "Asked at"?: string;
  Conversation?: string;
  Model?: string;
  Name: string;
  /**
   * relation → GEOPrompts
   */
  Prompt?: string[];
  Provider?: "claude";
  /**
   * relation → GEOResults
   */
  Read?: string[];
  /**
   * relation → GEOSearches
   */
  Searches?: string[];
  "Stop reason"?: string;
}
