// Generated by `sflock pull --agent geo` from GEOAnswers.json. Do not edit — re-pull.

export interface GEOAnswers {
  Answer?: string;
  /**
   * ISO 8601 date or date-time
   */
  "Asked at"?: string;
  Conversation?: string;
  Model?: string;
  Name: string;
  /**
   * relation → GEOResults
   */
  Pages?: string[];
  /**
   * relation → GEOPrompts
   */
  Prompt?: string[];
  Provider?: "claude";
  /**
   * relation → GEOQueries
   */
  Queries?: string[];
  Sources?: string;
  "Stop reason"?: string;
}
