// Generated by `sflock pull --agent geo` (notion:8320e9d6-a66d-4e79-a75b-dcfb09373231). Do not edit — re-pull.

export interface GEOAnswers {
  Answer?: string;
  /**
   * ISO 8601 date or date-time
   */
  "Asked at"?: string;
  Conversation?: string;
  Model?: string;
  Name: string;
  /**
   * relation → 9505a816-bd1a-4f8f-9a5c-0872f1079ebc
   */
  Prompt?: string[];
  Provider?: "claude";
  /**
   * relation → 9c9a9e4e-f0bd-4829-97ee-1ea7842a6e8b
   */
  Queries?: string[];
  Sources?: string;
  "Stop reason"?: string;
}
