// Generated by `sflock pull --agent geo` (notion:9505a816-bd1a-4f8f-9a5c-0872f1079ebc). Do not edit — re-pull.

export interface GEOPrompts {
  /**
   * relation → 8320e9d6-a66d-4e79-a75b-dcfb09373231
   */
  Answers?: string[];
  Prompt: string;
}
