// Generated by `sflock pull --agent geo` from GEOQueries.json. Do not edit — re-pull.

export interface GEOQueries {
  /**
   * relation → GEOAnswers
   */
  Answers?: string[];
  Engine?: "brave";
  Key: string;
  Query?: string;
  /**
   * relation → GEOResults
   */
  Results?: string[];
  /**
   * ISO 8601 date or date-time
   */
  "Searched at"?: string;
}
