// Generated by `sflock pull --agent geo` (notion:9c9a9e4e-f0bd-4829-97ee-1ea7842a6e8b). Do not edit — re-pull.

export interface GEOQueries {
  /**
   * relation → 8320e9d6-a66d-4e79-a75b-dcfb09373231
   */
  Answers?: string[];
  Engine?: "brave";
  Key: string;
  Query?: string;
  /**
   * relation → 6803195c-4024-4622-87b7-e79ebbae9d07
   */
  Results?: string[];
  /**
   * ISO 8601 date or date-time
   */
  "Searched at"?: string;
}
