// Generated by `sflock pull --agent geo` from GEOResults.json. Do not edit — re-pull.

export interface GEOResults {
  Age?: string;
  /**
   * relation → GEOAnswers
   */
  Answers?: string[];
  Brand?: string;
  Error?: string;
  /**
   * ISO 8601 date or date-time
   */
  "Fetched at"?: string;
  "Final URL"?: string;
  Key: string;
  Mentions?: number;
  /**
   * relation → GEOQueries
   */
  Query?: string[];
  Rank?: number;
  Snippet?: string;
  Status?: number;
  "Text length"?: number;
  Title?: string;
  URL?: string;
}
