// Generated by `sflock pull --agent geo` from GEOResults.json. Do not edit — re-pull.

export interface GEOResults {
  Conversation?: string;
  Error?: string;
  /**
   * ISO 8601 date or date-time
   */
  "Fetched at"?: string;
  "Final URL"?: string;
  Status?: number;
  "Text length"?: number;
  URL: string;
}
