// Generated by `sflock pull --agent geo` from GEOSearches.json. Do not edit — re-pull.

export interface GEOSearches {
  Conversation?: string;
  Egress?: string;
  Engine?: "brave";
  Error?: string;
  Key?: string;
  Name: string;
  /**
   * ISO 8601 date or date-time
   */
  "Searched at"?: string;
}
