// Generated by `sflock pull --agent geo` from GEOSearches.json. Do not edit — re-pull.

export interface GEOSearches {
  /**
   * relation → GEOAnswers
   */
  Answer?: string[];
  Egress?: string;
  Engine?: "brave";
  Error?: string;
  Key?: string;
  Name: string;
  /**
   * relation → GEOResults
   */
  Results?: string[];
  /**
   * ISO 8601 date or date-time
   */
  "Searched at"?: string;
}
