// Generated by `sflock pull --agent reddit-engage` from Decisions.json. Do not edit — re-pull.

export interface Decisions {
  /**
   * relation → Decisions
   */
  "Depends on"?: string[];
  "Draft output"?: string;
  Feedback?: string;
  "Final output"?: string;
  "Final reasoning"?: string;
  Input?: string;
  "Instructions hash"?: string;
  Kind?: "Reddit Thread Qualification" | "Reddit Reply" | "Reddit Reply Judge";
  Model?: string;
  Name: string;
  Output?: string;
  Reasoning?: string;
  /**
   * relation → RedditBacklog
   */
  "Reddit Backlog"?: string[];
  /**
   * relation → RedditThreads
   */
  "Reddit Thread"?: string[];
  Subject?: string;
  /**
   * relation → Decisions
   */
  Unlocks?: string[];
}
