// Generated by `sflock pull --agent reddit-engage` from RedditBacklog.json. Do not edit — re-pull.

export interface RedditBacklog {
  "Comment URL"?: string;
  /**
   * relation → Decisions
   */
  Decision?: string[];
  Name: string;
  Person?: string;
  /**
   * ISO 8601 date or date-time
   */
  "Posted at"?: string;
  Status?: "Pending approval" | "Waiting for OP" | "Dropped";
  /**
   * relation → RedditThreads
   */
  Thread?: string[];
  "Thread URL"?: string;
}
