// Generated by `sflock pull --agent reddit-engage` (notion:287eec98-859f-4a64-a50d-75da2e965488). Do not edit — re-pull.

export interface RedditThreads {
  Author?: string;
  Comments?: number;
  /**
   * ISO 8601 date or date-time
   */
  Created?: string;
  /**
   * relation → eddcfaaf-e6f1-4cea-a112-2b9d98426eb4
   */
  Decision?: string[];
  Name: string;
  Preview?: string;
  /**
   * ISO 8601 date or date-time
   */
  "Scanned at"?: string;
  Score?: number;
  Status?:
    "To qualify" | "Qualification pending review" | "To engage" | "Draft pending review" | "Approved" | "Not qualified";
  Subreddit?: string;
  Thread?: string;
  "Thread URL"?: string;
  Tier?: "T1" | "T2" | "No";
}
