// Generated by `sflock pull --agent reddit-engage` (notion:ba8786a2-afd6-4b12-8416-df2a85440f58). Do not edit — re-pull.

export interface RedditBacklog {
  "Comment URL"?: string;
  /**
   * relation → eddcfaaf-e6f1-4cea-a112-2b9d98426eb4
   */
  Decision?: string[];
  Name: string;
  Person?: string;
  /**
   * ISO 8601 date or date-time
   */
  "Posted at"?: string;
  Status?: "Pending approval" | "Waiting for OP" | "Dropped";
  /**
   * relation → 287eec98-859f-4a64-a50d-75da2e965488
   */
  Thread?: string[];
  "Thread URL"?: string;
}
