// Generated by `sflock pull --agent reddit-engage` from RedditThreads.json. Do not edit — re-pull.

export interface RedditThreads {
  Author?: string;
  /**
   * relation → RedditBacklog
   */
  Backlog?: string[];
  Comments?: number;
  /**
   * ISO 8601 date or date-time
   */
  Created?: string;
  /**
   * relation → Decisions
   */
  Decision?: string[];
  Name: string;
  Preview?: string;
  /**
   * ISO 8601 date or date-time
   */
  "Scanned at"?: string;
  Score?: number;
  Subreddit?: string;
  Thread?: string;
  "Thread URL"?: string;
  Tier?: "T1" | "T2" | "No";
}
