// Generated by `sflock bind` from *.scripts.ts. Do not edit — re-bind.

export interface Card {
  name?: string | null;
  /**
   * Full About prose with line breaks preserved; null if the profile has no About section.
   */
  about?: string | null;
  headline?: string | null;
  location?: string | null;
  profileUrl: string;
}

export interface Experience {
  positions: {
    title: string | null;
    company: string | null;
    duration: string | null;
    location: string | null;
    dateRange: string | null;
    /**
     * LinkedIn /company/ or /school/ page; null when the org has no LinkedIn page
     */
    companyUrl: string | null;
    description: string | null;
    employmentType: string | null;
  }[];
}

export interface Education {
  education: {
    degree: string | null;
    school: string | null;
    /**
     * null when the profile lists no dates for the entry
     */
    dateRange: string | null;
    /**
     * LinkedIn /school/ page; null when the school has no LinkedIn page
     */
    schoolUrl: string | null;
    description: string | null;
  }[];
}

export interface Posts {
  posts: {
    /**
     * urn:li:activity:<id>, from the card's data-urn.
     */
    urn: string;
    /**
     * Post commentary text; null when the post is media-only.
     */
    text?: string | null;
    /**
     * Display name of the entry's author (the original poster, or the repost source).
     */
    author?: string | null;
    /**
     * Permalink built from the urn.
     */
    postUrl: string;
    /**
     * Repost count as rendered; null when none.
     */
    reposts?: string | null;
    /**
     * Comment count as rendered; null when none.
     */
    comments?: string | null;
    /**
     * Author's headline/subtitle as rendered.
     */
    headline?: string | null;
    /**
     * Relative age, e.g. '2mo', '1w'; for a repost, when it was reposted, not the original time.
     */
    postedAgo?: string | null;
    /**
     * Reaction count as rendered, e.g. '27'; null when none.
     */
    reactions?: string | null;
    /**
     * Who reposted it into this profile's feed; null on an original (non-repost) entry.
     */
    repostedBy?: string | null;
    /**
     * True when the entry wraps quoted content (repost with thoughts).
     */
    isQuoteReshare: boolean;
  }[];
}

export interface Comments {
  comments: {
    /**
     * The post the comment was made on (from the comment's data-id, not the feed-wrapper card urn).
     */
    post: {
      url: string | null;
      /**
       * urn:li:activity:<postActivityId>.
       */
      urn: string | null;
      text?: string | null;
      author?: string | null;
      postedAgo?: string | null;
      authorHeadline?: string | null;
    };
    /**
     * The owner's comment text (full; null if the comment is media-only).
     */
    text?: string | null;
    /**
     * Relative age of the comment, e.g. '49m', '1d', '1w'.
     */
    postedAgo?: string | null;
    /**
     * Reaction count on the comment as rendered, e.g. '2'; null when none.
     */
    reactions?: string | null;
    /**
     * Comment identity: urn:li:comment:(activity:<postActivityId>,<commentId>).
     */
    commentUrn: string;
  }[];
}

export interface Company {
  name: string;
  phone?: string | null;
  logoUrl?: string | null;
  tagline?: string | null;
  /**
   * Inner numeric LinkedIn company ID from urn:li:fsd_company:N (e.g. 18834371 for almapay). Stable join key.
   */
  companyId: string;
  locations?: {
    city?: string | null;
    line1?: string | null;
    line2?: string | null;
    country?: string | null;
    postalCode?: string | null;
    isHeadquarter?: boolean;
    geographicArea?: string | null;
  }[];
  industries?: string[];
  /**
   * Company-declared website, returned verbatim — can be a linkedin.com self-link when the company set its own LinkedIn page as website (seen on stealth pages). Not normalized; filter linkedin.com values downstream if you need a real external site.
   */
  websiteUrl?: string | null;
  description?: string | null;
  foundedYear?: number | null;
  linkedinUrl?: string | null;
  headquarters?: {
    city?: string | null;
    line1?: string | null;
    line2?: string | null;
    country?: string | null;
    postalCode?: string | null;
    geographicArea?: string | null;
  } | null;
  specialities?: string[];
  /**
   * Count of LinkedIn members associated with the page, not the declared size — on catch-all/stealth pages it can wildly exceed employeeCountRange (battle-tested: 5,933 members on a page declaring 2-10). Use employeeCountRange for the company's self-declared size.
   */
  employeeCount?: number | null;
  followerCount?: number | null;
  /**
   * Canonical slug as LinkedIn returns it — may differ from the requested one if the page was renamed/redirected.
   */
  universalName: string;
  employeeCountRange?: {
    /**
     * null for open-ended ranges like 10K+
     */
    end?: number | null;
    start?: number | null;
  } | null;
}
