// Generated by `sflock pull --agent former-rpa-pms` (notion:b9b4d7b7-884c-8368-80d9-070bdf14ef0f). Do not edit — re-pull.

export interface Companies {
  Aliases?: string;
  Description?: string;
  Founded?: number;
  Headcount?: number;
  HQ?: string;
  Industry?: string;
  /**
   * relation → 9c04d7b7-884c-820b-b2a2-874c61f00074
   */
  Jobs?: string[];
  "Last Funding"?: string;
  "LinkedIn URL"?: string;
  Name: string;
  Source?: (
    | "wttj_job"
    | "experience"
    | "manual"
    | "Job posting"
    | "L"
    | "o"
    | "g"
    | "i"
    | "s"
    | "t"
    | "c"
    | " "
    | "v"
    | "e"
    | "r"
    | "a"
    | "h"
    | "u"
    | "n"
    | "More Jobs Discovery"
  )[];
  Tagline?: string;
  Website?: string;
}
