// Generated by `sflock pull --agent former-rpa-pms` (notion:e976116e-fcf0-42d4-bc16-99fa9c801e1c). Do not edit — re-pull.

export interface Leads {
  /**
   * relation → eddcfaaf-e6f1-4cea-a112-2b9d98426eb4
   */
  Decision?: string[];
  "LinkedIn URL"?: string;
  Name: string;
  /**
   * relation → 180ff6c9-e29d-4853-adf5-754948a20fe4
   */
  Person?: string[];
  Status?:
    | "To pre-qualify"
    | "To enrich"
    | "To qualify"
    | "Qualification pending approval"
    | "Not qualified"
    | "To engage"
    | "Engagement pending approval"
    | "Engaged - waiting for lead"
    | "Meeting booked";
}
