// Generated by `sflock bind` from *.scripts.ts. Do not edit — re-bind.

export interface Threads {
  count: number;
  threads: {
    url: string;
    /**
     * The post's full body text, never truncated; null for link/image posts.
     */
    body?: string | null;
    score?: number;
    title: string;
    author?: string | null;
    created: string;
    post_type?: string | null;
    num_comments?: number;
  }[];
  subreddit: string;
}
