// Generated by `sflock bind` from *.scripts.ts. Do not edit — re-bind.

export interface Threads {
  count: number;
  threads: {
    url: string;
    /**
     * The post's full body text, never truncated; null for link/image posts.
     */
    body?: string | null;
    score?: number;
    title: string;
    author?: string | null;
    created: string;
    post_type?: string | null;
    num_comments?: number;
  }[];
  subreddit: string;
}

export interface Info {
  id?: string | null;
  rules?:
    | {
        body?: string | null;
        title?: string | null;
      }[]
    | null;
  title?: string | null;
  /**
   * Page-reported reason when banned/private
   */
  detail?: string | null;
  /**
   * Visibility as the page reports it: public/restricted/..., or banned/private
   */
  status: string;
  created?: string | null;
  subreddit: string;
  moderators?:
    | {
        joined?: string | null;
        username?: string;
        permissions?: string | null;
      }[]
    | null;
  description?: string | null;
  weekly_active_users?: number | null;
  weekly_contributions?: number | null;
}
