// Generated by `sflock bind` from *.scripts.ts. Do not edit — re-bind.

export interface Threads {
  count: number;
  threads: {
    url: string;
    /**
     * The post's full body text, never truncated; null for link/image posts.
     */
    body?: string | null;
    score?: number;
    title: string;
    author?: string | null;
    created: string;
    post_type?: string | null;
    num_comments?: number;
  }[];
  subreddit: string;
}

export interface Thread {
  /**
   * Reddit fullname, e.g. t3_1ldvy4n
   */
  id: string;
  score: number;
  title: string;
  author: string;
  domain?: string | null;
  created: string;
  op_text: string;
  comments: {
    /**
     * Comment fullname, e.g. t1_myeuclu
     */
    id: string;
    body: string;
    /**
     * Reply nesting level; with array order (thread order) reconstructs the tree
     */
    depth: number;
    score?: number | null;
    author: string | null;
    created: string | null;
    permalink?: string | null;
  }[];
  permalink: string;
  post_type: string;
  subreddit: string;
  /**
   * Submission target: external link for link posts, the thread url for self posts
   */
  content_href?: string | null;
  /**
   * Reddit's total comment count; compare with comments.length to detect on-load truncation
   */
  num_comments: number;
  upvote_ratio?: number | null;
}

export interface Info {
  id?: string | null;
  rules?:
    | {
        body?: string | null;
        title?: string | null;
      }[]
    | null;
  title?: string | null;
  /**
   * Page-reported reason when banned/private
   */
  detail?: string | null;
  /**
   * Visibility as the page reports it: public/restricted/..., or banned/private
   */
  status: string;
  created?: string | null;
  subreddit: string;
  moderators?:
    | {
        joined?: string | null;
        username?: string;
        permissions?: string | null;
      }[]
    | null;
  description?: string | null;
  weekly_active_users?: number | null;
  weekly_contributions?: number | null;
}
