// Generated by `sflock bind` from *.scripts.ts. Do not edit — re-bind.

export interface Ask {
  /**
   * The assistant's full answer as the markdown source the model emitted (the stream's `text` blocks, concatenated in order). Not the rendered text: the reasoning card and tool-call cards are separate block types and are excluded, and citation pills stay markdown rather than flattening into prose.
   */
  answer: string;
  /**
   * Every source the model's tools surfaced: each result web_search returned and each page web_fetch loaded, deduped by url. This is the candidate pool the model read, NOT only the sources the answer cites — a one-line answer routinely carries a dozen. Empty when no tool ran.
   */
  sources: {
    url: string;
    /**
     * Which tool surfaced it: "web_search" (a result) or "web_fetch" (a page it loaded).
     */
    tool: string | null;
    /**
     * Page title as the tool reported it (may carry raw HTML comment artifacts, as it does on screen).
     */
    title: string | null;
    /**
     * Human-readable site name, e.g. "npm".
     */
    siteName: string | null;
    /**
     * Source domain as attributed on screen, e.g. "npmjs.com".
     */
    siteDomain: string | null;
  }[];
  /**
   * uuid of the assistant message, from the stream's message_start.
   */
  messageId: string;
  /**
   * Why generation ended, verbatim from the stream: "end_turn" for a complete answer, anything else (e.g. "max_tokens") means the answer is truncated. Null when the stream carried no message_delta.
   */
  stopReason: string | null;
  /**
   * Conversation uuid, read off the completion endpoint's own URL (never null — claude.ai has no anonymous chat).
   */
  conversationId: string;
  /**
   * Search queries the model issued via its web_search tool during this answer. Empty when it didn't search.
   */
  webSearchQueries: string[];
}

export interface Search {
  /**
   * How many result cards were extracted from THIS page — literally results.length. NOT a match count and NOT an estimate of what Brave holds for the query; there is no such number on the page. A full page reads ~16-20.
   */
  count: number;
  query: string;
  offset: number;
  /**
   * The page's organic web results, in rank order. EMPTY ONLY WHEN BRAVE SAID SO — see `emptyBecause`. If this script reads zero rows off a page that Brave answered normally it THROWS instead of returning [], because a silent empty is indistinguishable from a real one to any schema and would be read as 'the domain has nothing on this topic'.
   */
  results: {
    /**
     * Date chip Brave renders before the snippet — absolute ('April 28, 2026') or relative ('3 weeks ago'). null when absent.
     */
    age?: string | null;
    url: string;
    title: string;
    /**
     * Clean description body, with Brave's leading date chip removed (see age). null when the card has no description. NOTE: a page Brave holds by URL but has never read carries the literal placeholder 'We cannot provide a description for this page right now' here — that is a string, not null.
     */
    snippet?: string | null;
  }[];
  /**
   * What Brave actually searched if it ANNOUNCED an auto-rewrite, else null. Read off the English 'Showing results for' line, so it stays null on a localized SERP — and also, measured, when Brave silently corrects a typo and announces nothing. null therefore means 'no rewrite was announced', never 'the literal query was searched'.
   */
  rewrittenTo?: string | null;
  /**
   * Why `results` is empty, in Brave's own terms — and null whenever `results` is non-empty. One of: the operators were relaxed (too few documents matched them), Brave's no-matches banner, or its no-results message. This is what makes an empty answer READABLE: an empty set is a fact about the query, never a scraper failure, because the failure case throws.
   */
  emptyBecause: string | null;
  /**
   * Whether Brave honored the operators in `query`. false = Brave found too few matching documents, dropped the operators and answered a RELAXED query instead (it shows a 'search operators were not applied — Too few matches were found' banner): `results` are then soft relevance over the whole web, NOT filtered, so treat them as empty for any hard-filter use such as a site: coverage check. ONLY MEANINGFUL WHEN `query` CONTAINS AN OPERATOR — for an operator-free query it is vacuously true. Detected language-independently via the banner's /help/operators link, with the English sentence as a fallback; either signal reports false, so it errs toward warning you.
   */
  operatorsApplied: boolean;
}

export interface Submit {
  /**
   * The URL that was submitted, echoed back from the args.
   */
  url: string;
  /**
   * The panel's explanatory line, verbatim ('Thank you for your submission.' / 'Please insert a valid URL.'). This is where Brave states WHY a submission was rejected. null when the panel has no detail row — kept nullable because only the success and invalid-URL variants have been observed.
   */
  detail: string | null;
  /**
   * The outcome panel's heading, verbatim as rendered ('Success' / 'Error'). Localized by Brave, so branch on `accepted` instead. Required and non-empty on purpose: Brave shows a 'Verifying you're a human being' step in the SAME panel before deciding, and that intermediate state has no heading — so a missing one means the script read the panel before the verdict existed, which must fail loudly rather than validate as a successful submission.
   */
  heading: string;
  /**
   * Whether Brave accepted the submission: true = the success panel, false = the error panel (e.g. a malformed URL). Read off the panel's own `error` class, not its wording, so it survives localization. Acceptance is a queued re-fetch request only — it carries no promise that the page gets crawled, indexed or ranked.
   */
  accepted: boolean;
}
