// Generated by `sflock bind` from *.scripts.ts. Do not edit — re-bind.
//
// EXCEPT it is not, yet: `bind` reads a contract through the REST door (`GET /scripts/<host>/<slug>`)
// and that door currently 500s on any catalogue script whose `sideEffects` holds a value outside
// none|undetermined|write — all three of these do. `reduck read` fails identically, so it is the
// server, not the client. These types were transcribed by hand from the contracts as the MCP door
// returns them (`read_script`), which is the same JSON. Re-run `sflock bind --client geo` and delete
// this note the day that door is fixed.

export interface Ask {
  /**
   * The assistant's full answer as the markdown source the model emitted.
   */
  answer: string;
  /**
   * uuid of the assistant message.
   */
  messageId: string;
  /**
   * Conversation uuid — never null, claude.ai has no anonymous chat.
   */
  conversationId: string;
  /**
   * Why generation ended: "end_turn" for a complete answer, anything else means it is truncated.
   */
  stopReason?: string | null;
  /**
   * Search queries the model issued via its web_search tool. Empty when it didn't search.
   */
  webSearchQueries: string[];
  /**
   * Every source the model's tools surfaced — the candidate pool it READ, not only what the
   * answer cites. Empty when no tool ran.
   */
  sources: {
    url: string;
    /**
     * Which tool surfaced it: "web_search" (a result) or "web_fetch" (a page it loaded).
     */
    tool?: string | null;
    title?: string | null;
    siteName?: string | null;
    siteDomain?: string | null;
  }[];
}

export interface Search {
  query: string;
  offset: number;
  count: number;
  results: {
    title: string;
    url: string;
    /**
     * Date chip Brave renders before the snippet — absolute or relative. null when absent.
     */
    age?: string | null;
    /**
     * Clean description body. A page Brave holds by URL but has never READ carries the literal
     * placeholder "We cannot provide a description for this page right now" here — a string, not null.
     */
    snippet?: string | null;
  }[];
  /**
   * false = Brave found too few matching documents, dropped the operators and answered a RELAXED
   * query, so `results` are soft relevance over the whole web and not filtered at all. Vacuously
   * true for a query carrying no operators, so only read it when you passed one.
   */
  operatorsApplied: boolean;
  /**
   * What Brave actually searched if it auto-rewrote the query, else null.
   */
  rewrittenTo?: string | null;
}

export interface Submit {
  url: string;
  /**
   * Whether Brave accepted the submission — a queued re-fetch request only, never a promise that
   * the page gets crawled, indexed or ranked.
   */
  accepted: boolean;
  heading: string;
  detail?: string | null;
}
