// Generated by `sflock pull --client notion --model eddcfaaf-e6f1-4cea-a112-2b9d98426eb4`. Do not edit — re-pull.

export interface Decisions {
  Decision?: "Qualified" | "Not qualified";
  Evidence?: string;
  /**
   * relation → e976116e-fcf0-42d4-bc16-99fa9c801e1c
   */
  Lead?: string[];
  Name: string;
  Prompt?: string;
  Reasoning?: string;
}
