// Generated by `sflock pull --agent linkedin-leads` (notion:eddcfaaf-e6f1-4cea-a112-2b9d98426eb4). Do not edit — re-pull.

export interface Decisions {
  Accepted?: "Accepted" | "Rejected";
  Feedback?: string;
  "Ground truth"?: string;
  "Human verdict"?: "Accepted" | "Rejected";
  "Include as example"?: boolean;
  Input?: string;
  /**
   * relation → e976116e-fcf0-42d4-bc16-99fa9c801e1c
   */
  Lead?: string[];
  Name: string;
  Output?: string;
  /**
   * relation → 942c4138-c9db-404c-9ae0-472f8edb0712
   */
  Prompt?: string[];
  Reasoning?: string;
}
