// Generated by `sflock pull --agent linkedin-leads` (notion:180ff6c9-e29d-4853-adf5-754948a20fe4). Do not edit — re-pull.

export interface People {
  About?: string;
  Activity?: string;
  Experiences?: string;
  Headline?: string;
  "LinkedIn URL"?: string;
  Location?: string;
  Name: string;
  /**
   * ISO 8601 date or date-time
   */
  Updated?: string;
}
