// Generated by `sflock pull --client notion --model 942c4138-c9db-404c-9ae0-472f8edb0712`. Do not edit — re-pull.

export interface Prompts {
  Instruction?: string;
  Name: string;
  "System prompt"?: string;
}
