// Generated by `sflock pull --agent linkedin-leads` (notion:028210ed-fc1f-40e1-ba7d-ea28f68ba6fe). Do not edit — re-pull.

export interface Sourcing {
  Args?: string;
  Name: string;
  /**
   * relation → 180ff6c9-e29d-4853-adf5-754948a20fe4
   */
  People?: string[];
  /**
   * ISO 8601 date or date-time
   */
  "Ran at"?: string;
  Script?: string;
}
