// Generated by `sflock bind` from *.scripts.ts. Do not edit — re-bind.

export type Search = {
  /**
   * Canonical result URL; Google's /url?q= wrapper is stripped.
   */
  url: string;
  /**
   * Reactions/comments/date chip from cite[role=text] (e.g. '750+ reactions', '1 week ago'). Empty when absent.
   */
  meta: string;
  /**
   * Text before the ' · ' separator in the source row's first line (e.g. 'LinkedIn', 'Reddit').
   */
  site: string;
  /**
   * The <h3> headline.
   */
  title: string;
  /**
   * Text after the ' · ' separator in the source row's first line (person, subreddit, handle). Empty when absent.
   */
  byline: string;
  /**
   * Body text of the result card.
   */
  snippet: string;
}[];
