// Generated by `sflock pull --agent lk-engage` (notion:8058e760-5510-46e4-855b-18d82282a21a). Do not edit — re-pull.

export interface LkEngagements {
  Author?: string;
  "Author name"?: string;
  /**
   * relation → eddcfaaf-e6f1-4cea-a112-2b9d98426eb4
   */
  Decision?: string[];
  Name: string;
  Post?: string;
  "Post URL"?: string;
  Reach?: number;
  /**
   * ISO 8601 date or date-time
   */
  "Scanned at"?: string;
  Status?:
    "To qualify" | "Qualification pending review" | "To engage" | "Draft pending review" | "Approved" | "Not qualified";
}
