// Generated by `sflock bind` from *.scripts.ts. Do not edit — re-bind.

export interface Search {
  /**
   * Number of tweets returned. 0 is a first-class outcome (no results for the query).
   */
  count: number;
  query: string;
  tweets: {
    url: string;
    /**
     * Tweet creation date as returned by X, e.g. 'Tue Jun 09 13:47:27 +0000 2026'.
     */
    date: string;
    name?: string;
    /**
     * Full tweet text (long-form note tweets included).
     */
    text: string;
    likes: number;
    /**
     * 0 when X does not expose views for this tweet.
     */
    views?: number;
    handle: string;
    quotes?: number;
    replies: number;
    retweets: number;
    followers?: number | null;
  }[];
}

export interface Feed {
  tweets: {
    /**
     * Tweet rest_id. Note: for retweets this is the retweet wrapper id, not the original — join via retweeted_tweet.id.
     */
    id: string;
    url: string;
    lang?: string | null;
    /**
     * Full tweet text. Long-form (>280) is sourced from note_tweet when present.
     */
    text: string;
    author: {
      id: string;
      name: string;
      handle: string;
    };
    is_quote: boolean;
    /**
     * X's native format e.g. 'Fri May 29 02:06:57 +0000 2026'.
     */
    created_at: string;
    is_retweet: boolean;
    like_count: number;
    /**
     * null when views are not exposed for this tweet.
     */
    view_count: number | null;
    /**
     * The tweet this one replies to, from X's native in_reply_to_status_id_str / in_reply_to_screen_name. null unless this tweet is a reply — so `in_reply_to != null` is the reply test.
     */
    in_reply_to?: {
      id: string;
      author_handle: string | null;
    } | null;
    quote_count: number;
    reply_count: number;
    quoted_tweet?: {
      id: string;
      author_handle: string | null;
    } | null;
    retweet_count: number;
    bookmark_count?: number;
    retweeted_tweet?: {
      id: string;
      author_handle: string | null;
    } | null;
  }[];
}

export interface Tweet {
  /**
   * Number of replies returned. 0 is a first-class outcome (no replies, or replies hidden).
   */
  count: number;
  /**
   * The tweet at tweet_url itself (the conversation focal/root); null if it can't be found (deleted / tombstoned).
   */
  tweet: {
    id?: string;
    url?: string;
    text?: string;
    likes?: number;
    author?: string;
    quotes?: number;
    replies?: number;
    retweets?: number;
    created_at?: string;
    author_name?: string;
    /**
     * Parent tweet id when the focal tweet is itself a reply; null when it is a root.
     */
    in_reply_to?: string | null;
  } | null;
  replies: {
    id: string;
    url: string;
    text: string;
    likes?: number;
    author: string;
    quotes?: number;
    replies?: number;
    retweets?: number;
    created_at?: string;
    author_name?: string;
    in_reply_to?: string | null;
  }[];
  tweet_id: string;
}

export interface UserInfo {
  bio?: string | null;
  name: string;
  /**
   * Canonical handle as returned by X (may differ in casing from the input).
   */
  handle: string;
  /**
   * Account creation date in X's format, e.g. 'Tue Jun 02 20:12:29 +0000 2009'.
   */
  joined?: string | null;
  /**
   * True when the authenticated viewer owns this profile.
   */
  is_self: boolean;
  /**
   * Numeric rest_id. Always present, including your own profile.
   */
  user_id: string;
  /**
   * Expanded profile URL (full https link, not the display text).
   */
  website?: string | null;
  location?: string | null;
  /**
   * Whether they follow you.
   */
  follows_you: boolean;
  /**
   * Blue/verified badge (is_blue_verified).
   */
  is_verified: boolean;
  /**
   * Whether you follow them; null on your own profile.
   */
  is_following: boolean | null;
  followers_count?: number | null;
  following_count?: number | null;
}

export type UserPosts = {
  id: string;
  url: string;
  lang?: string | null;
  text: string;
  likes?: number | null;
  views?: string | null;
  quotes?: number | null;
  replies?: number | null;
  is_quote?: boolean | null;
  retweets?: number | null;
  bookmarks?: number | null;
  created_at: string;
  is_retweet?: boolean | null;
}[];

export type UserReplies = {
  id: string;
  url: string;
  lang?: string | null;
  text: string;
  likes?: number | null;
  views?: string | null;
  quotes?: number | null;
  replies?: number | null;
  is_quote?: boolean | null;
  retweets?: number | null;
  bookmarks?: number | null;
  created_at: string;
  is_retweet?: boolean | null;
  /**
   * Tweet id this row replies to; null on a plain post. Feed to get_tweet for the parent.
   */
  in_reply_to_id?: string | null;
  /**
   * Handle this row replies to; null on a plain post.
   */
  in_reply_to_handle?: string | null;
}[];

export interface Reply {
  url: string;
  text: string;
  handle: string;
  tweet_id: string;
  /**
   * id of the parent tweet
   */
  in_reply_to: string;
}
