// Generated by `sflock bind` from *.scripts.ts. Do not edit — re-bind.

export interface Search {
  /**
   * Number of tweets returned. 0 is a first-class outcome (no results for the query).
   */
  count: number;
  query: string;
  tweets: {
    id: string;
    url: string;
    lang?: string | null;
    /**
     * Full tweet text; long-form (>280) sourced from note_tweet when present.
     */
    text: string;
    likes?: number | null;
    /**
     * null when X does not expose views for this tweet.
     */
    views?: number | null;
    author: {
      id: string | null;
      name: string | null;
      handle: string | null;
    } | null;
    quotes?: number | null;
    replies?: number | null;
    is_quote?: boolean;
    retweets?: number | null;
    bookmarks?: number | null;
    /**
     * Author's follower count (search enrichment; not part of the canonical tweet shape).
     */
    followers?: number | null;
    /**
     * X's native format, e.g. 'Tue Jun 09 13:47:27 +0000 2026'.
     */
    created_at: string;
    is_retweet?: boolean;
  }[];
}

export interface Feed {
  tweets: {
    /**
     * Tweet rest_id. For retweets this is the wrapper id, not the original — join via retweeted_tweet.id.
     */
    id: string;
    url: string;
    lang?: string | null;
    /**
     * Full tweet text; long-form (>280) sourced from note_tweet when present.
     */
    text: string;
    likes: number | null;
    /**
     * null when X does not expose views for this tweet.
     */
    views?: number | null;
    author: {
      id: string;
      name: string;
      handle: string;
    };
    quotes: number | null;
    replies: number | null;
    is_quote: boolean;
    retweets: number | null;
    bookmarks?: number | null;
    /**
     * X's native format, e.g. 'Fri May 29 02:06:57 +0000 2026'.
     */
    created_at: string;
    is_retweet: boolean;
    /**
     * The tweet this replies to; null unless a reply (so in_reply_to != null is the reply test).
     */
    in_reply_to?: {
      id: string;
      author_handle: string | null;
    } | null;
    quoted_tweet?: {
      id: string;
      author_handle: string | null;
    } | null;
    retweeted_tweet?: {
      id: string;
      author_handle: string | null;
    } | null;
  }[];
}

export interface Tweet {
  /**
   * Number of replies returned. 0 is a first-class outcome (no replies, or replies hidden).
   */
  count: number;
  /**
   * The tweet at tweet_url (the conversation focal/root); null if it can't be found (deleted / tombstoned).
   */
  tweet: {
    id: string;
    url: string;
    lang?: string | null;
    /**
     * Full tweet text; long-form (>280) sourced from note_tweet when present.
     */
    text: string;
    likes?: number | null;
    /**
     * null when X does not expose views for this tweet.
     */
    views?: number | null;
    author?: {
      id: string | null;
      name: string | null;
      handle: string | null;
    } | null;
    quotes?: number | null;
    replies?: number | null;
    is_quote?: boolean;
    retweets?: number | null;
    bookmarks?: number | null;
    created_at: string;
    is_retweet?: boolean;
    /**
     * Parent tweet {id, author_handle} when the focal tweet is itself a reply; null when it is a root.
     */
    in_reply_to?: {
      id: string;
      author_handle: string | null;
    } | null;
  } | null;
  replies: {
    id: string;
    url: string;
    lang?: string | null;
    /**
     * Full tweet text; long-form (>280) sourced from note_tweet when present.
     */
    text: string;
    likes?: number | null;
    views?: number | null;
    author?: {
      id: string | null;
      name: string | null;
      handle: string | null;
    } | null;
    quotes?: number | null;
    replies?: number | null;
    is_quote?: boolean;
    retweets?: number | null;
    bookmarks?: number | null;
    created_at: string;
    is_retweet?: boolean;
    /**
     * The tweet this reply replies to, {id, author_handle}.
     */
    in_reply_to?: {
      id: string;
      author_handle: string | null;
    } | null;
  }[];
  /**
   * True iff the reply pull drained the conversation (no further page loaded, or a page added nothing) rather than stopping at count. False means it hit the cap and more replies may exist, so absence of a given reply is not proof. Nested Show-more-replies are not expanded, so true is a floor, not a guarantee every nested reply was seen.
   */
  complete: boolean;
  tweet_id: string;
}

export interface UserInfo {
  bio?: string | null;
  name: string;
  /**
   * Canonical handle as returned by X (may differ in casing from the input).
   */
  handle: string;
  /**
   * Account creation date in X's format, e.g. 'Tue Jun 02 20:12:29 +0000 2009'.
   */
  joined?: string | null;
  /**
   * True when the authenticated viewer owns this profile.
   */
  is_self: boolean;
  /**
   * Numeric rest_id. Always present, including your own profile.
   */
  user_id: string;
  /**
   * Expanded profile URL (full https link, not the display text).
   */
  website?: string | null;
  location?: string | null;
  /**
   * Whether they follow you.
   */
  follows_you: boolean;
  /**
   * Blue/verified badge (is_blue_verified).
   */
  is_verified: boolean;
  /**
   * Whether you follow them; null on your own profile.
   */
  is_following: boolean | null;
  followers_count?: number | null;
  following_count?: number | null;
}

export type UserPosts = {
  id: string;
  url: string;
  lang?: string | null;
  /**
   * Full tweet text; long-form (>280) sourced from note_tweet when present.
   */
  text: string;
  likes?: number | null;
  /**
   * null when X does not expose views for this tweet.
   */
  views?: number | null;
  quotes?: number | null;
  replies?: number | null;
  is_quote?: boolean;
  retweets?: number | null;
  bookmarks?: number | null;
  created_at: string;
  is_retweet?: boolean;
}[];

export type UserReplies = {
  id: string;
  url: string;
  lang?: string | null;
  /**
   * Full tweet text; long-form (>280) sourced from note_tweet when present.
   */
  text: string;
  likes?: number | null;
  /**
   * null when X does not expose views for this tweet.
   */
  views?: number | null;
  quotes?: number | null;
  replies?: number | null;
  is_quote?: boolean;
  retweets?: number | null;
  bookmarks?: number | null;
  created_at: string;
  is_retweet?: boolean;
  /**
   * The tweet this row replies to, {id, author_handle}; null on a plain post. Feed id to get_tweet for the parent.
   */
  in_reply_to?: {
    id: string;
    author_handle: string | null;
  } | null;
}[];

export interface Reply {
  url: string;
  text: string;
  handle: string;
  tweet_id: string;
  /**
   * id of the parent tweet
   */
  in_reply_to: string;
}
