// Generated by `sflock pull --agent x-engage` (notion:942c4138-c9db-404c-9ae0-472f8edb0712). Do not edit — re-pull.

export interface Prompts {
  "Anchor field"?: string;
  "Input schema"?: string;
  Instruction?: string;
  Name: string;
  "Output schema"?: string;
  Proposal?: string;
  "System prompt"?: string;
  Version?: number;
}
