// Generated by `sflock pull --agent x-engage` (notion:f33193c0-a57d-43cc-900c-c399e1c1beda). Do not edit — re-pull.

export interface XEngagements {
  Author?: string;
  "Author engagement"?: string;
  "Author name"?: string;
  /**
   * relation → eddcfaaf-e6f1-4cea-a112-2b9d98426eb4
   */
  Decision?: string[];
  Name: string;
  Post?: string;
  "Post URL"?: string;
  Reach?: number;
  /**
   * ISO 8601 date or date-time
   */
  "Scanned at"?: string;
  Status?: "To qualify" | "To engage" | "Not qualified" | "Draft pending review" | "Approved";
}
