// Generated by `sflock pull --agent x-engage` (notion:c93447b2-1c17-484d-a3c6-caef8893418c). Do not edit — re-pull.

export interface XPeople {
  Approved?: boolean;
  Handle?: string;
  Name: string;
}
