// Generated by `sflock pull --agent x-engage` (notion:895ce048-10e7-43f9-bd4f-7ff72a74ca05). Do not edit — re-pull.

export interface XPosts {
  Name: string;
  "Post URL"?: string;
  /**
   * ISO 8601 date or date-time
   */
  "Posted at"?: string;
  Text?: string;
  Views?: number;
}
