// Generated by `sflock pull --agent x-engage` (notion:88be9bab-eac8-4d6b-8a43-e0983c815728). Do not edit — re-pull.

export interface XReplies {
  Name: string;
  "Parent author"?: string;
  "Parent post"?: string;
  "Post URL"?: string;
  /**
   * ISO 8601 date or date-time
   */
  "Posted at"?: string;
  Reply?: string;
  "Reply URL"?: string;
  Source?: "Scraped" | "Validated draft" | "Manual";
}
