#!/usr/bin/env node
// sflock — the setup CLI. Compiles contracts (Ground Truth) into the TS types an agent uses.
//   sflock pull --agent <id>     an agent's destination models → agents/<id>/schema/<Model>.ts
//   sflock bind --client <name>  a reduck source's manifest     → src/clients/<name>/schema.ts
//
// pull reads the agent's config.ts (destination + model→table map) and, per model, asks the
// store to `describe` it (a JSON Schema) then compiles that to a TS type — no intermediate
// .json on disk, and the file is named by the model key. bind reads a source's script
// manifest and compiles each script's output schema. sflock holds no per-store semantics.

import "./env.js";
import { Command } from "commander";
import { mkdir, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { compile } from "json-schema-to-typescript";
import { bind } from "./scripts.js";
import { STORES, type AgentConfig } from "./stores/index.js";

// Writable-property count of a described model (a JSON Schema's `properties`) — for the
// progress line. Every store now emits JSON Schema, so there is one shape to read.
const propCount = (described: unknown): number =>
	Object.keys((described as { properties?: object }).properties ?? {}).length;

const program = new Command()
	.name("sflock")
	.description("Setup CLI — compile destination/source contracts into the TS types an agent uses.");

program
	.command("pull")
	.description("Compile each of an agent's models → agents/<agent>/schema/<Model>.ts (TS type)")
	.requiredOption("--agent <id>", "agent under agents/ whose config.ts names the destination + models")
	.action(async ({ agent }: { agent: string }) => {
		const agentDir = join("agents", agent);
		const ok = await stat(agentDir).then((s) => s.isDirectory()).catch(() => false);
		if (!ok) program.error(`no agent "${agent}" — ${agentDir}/ does not exist.`);
		const { default: config } = (await import(`../agents/${agent}/config.js`)) as { default: AgentConfig };
		const store = STORES[config.destination];
		const dir = join(agentDir, "schema");
		await mkdir(dir, { recursive: true });
		for (const [name, model] of Object.entries(config.models)) {
			const described = await store.describe(model);
			const ts = await compile(described as object, name, {
				bannerComment: `// Generated by \`sflock pull --agent ${agent}\` (${config.destination}:${model}). Do not edit — re-pull.`,
				additionalProperties: false
			});
			const path = join(dir, `${name}.ts`);
			await writeFile(path, ts);
			console.error(`${name}: ${propCount(described)} writable properties → ${path}`);
		}
	});

program
	.command("bind")
	.description("Compile a reduck source's script manifest → src/clients/<client>/schema.ts (TS output types)")
	.requiredOption("--client <name>", "source under src/clients/<name>/ with a scripts.ts manifest")
	.action(async ({ client }: { client: string }) => {
		const { scripts } = (await import(`./clients/${client}/scripts.js`)) as { scripts: Record<string, string> };
		const path = join("src", "clients", client, "schema.ts");
		await writeFile(path, await bind(scripts));
		console.error(`${client}: ${Object.keys(scripts).length} scripts → ${path}`);
	});

program.parseAsync().catch((e: Error) => {
	console.error(`error: ${e.message}`);
	process.exit(1);
});
