#!/usr/bin/env node
// sflock — the operator CLI: setup (compile contracts → TS types) plus read-only review of an
// agent's Decisions. Both are agent-agnostic — parameterized by --agent — and neither mutates the
// pipeline (that is the per-agent funnel binary's job).
//   sflock pull --agent <id>            an agent's destination models → agents/<id>/schema/<Model>.ts
//   sflock bind --client <name>         a reduck source's manifest     → src/clients/<name>/schema.ts
//   sflock decisions list --agent <id>  the review queue (or --reviewed/--all), each flagged hasFeedback/overturned
//   sflock decisions list --agent <id> --feedback   every decision I have given feedback on, with the feedback
//   sflock decisions show --agent <id> <decision> [--feedback]   one decision, or just its feedback
//   sflock prompts list --agent <id>    each decision kind's LIVE contract: version + fingerprint
//   sflock prompts show --agent <id> <kind>   one live contract in full (body, schemas, hash)
//   sflock docs list                    the Writer's documents (agent-agnostic — one shared table)
//   sflock docs show <doc>              one document, its body as markdown
//   sflock docs push <doc> [file]       a new version of one document — saved AND applied live in the
//                                       open editor (the one write sflock has; prose, never pipeline state)
//
// pull reads the agent's config.ts (destination + model→table map) and, per model, asks the
// store to `describe` it (a JSON Schema) then compiles that to a TS type — no intermediate
// .json on disk, and the file is named by the model key. bind reads a source's script
// manifest and compiles each script's output schema. decisions reads the shared CRM through
// createReviewer (no entity bridge); docs reads the Writer's table through the Store seam
// (src/docs.ts) — no --agent, because the writing table belongs to no one agent — and pushes through
// the app's own save sink, so a revision reaches the open editor. sflock holds no per-store semantics.

import "./env.js";
import { Command } from "commander";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { text } from "node:stream/consumers";
import { join } from "node:path";
import { compile } from "json-schema-to-typescript";
import { bind } from "./scripts.js";
import { renderError } from "./errors.js";
import { STORES } from "./stores/index.js";
import { createReviewer } from "./decide.js";
import * as writer from "./docs.js";
import { renderFeedback } from "./review.js";
import { AGENTS, type Agent } from "../agents/index.js";

// Writable-property count of a described model (a JSON Schema's `properties`) — for the
// progress line. Every store now emits JSON Schema, so there is one shape to read.
const propCount = (described: unknown): number =>
	Object.keys((described as { properties?: object }).properties ?? {}).length;

const program = new Command()
	.name("sflock")
	.description("Operator CLI — compile contracts into TS types, and inspect an agent's Decisions.");

// --agent → its registry entry (config + its own evidence renderer: decisions must display through
// the renderer that judged them). The roster is agents/index.ts — one registration per agent.
const loadAgent = (agent: string): Agent =>
	AGENTS[agent] ?? program.error(`no agent "${agent}" — register it in agents/index.ts.`);

program
	.command("pull")
	.description("Compile each of an agent's models → agents/<agent>/schema/<Model>.ts (TS type)")
	.requiredOption("--agent <id>", "agent under agents/ whose config.ts names the destination + models")
	.action(async ({ agent }: { agent: string }) => {
		const { config } = loadAgent(agent);
		const store = STORES[config.destination];
		const dir = join("agents", agent, "schema");
		await mkdir(dir, { recursive: true });
		for (const [name, model] of Object.entries(config.models)) {
			const described = await store.describe(model);
			const ts = await compile(described as object, name, {
				bannerComment: `// Generated by \`sflock pull --agent ${agent}\` (${config.destination}:${model}). Do not edit — re-pull.`,
				additionalProperties: false
			});
			const path = join(dir, `${name}.ts`);
			await writeFile(path, ts);
			console.error(`${name}: ${propCount(described)} writable properties → ${path}`);
		}
	});

program
	.command("bind")
	.description("Compile a reduck source's script manifest → src/clients/<client>/schema.ts (TS output types)")
	.requiredOption("--client <name>", "source under src/clients/<name>/ with a scripts.ts manifest")
	.action(async ({ client }: { client: string }) => {
		const { scripts } = (await import(`./clients/${client}/scripts.js`)) as { scripts: Record<string, string> };
		const path = join("src", "clients", client, "schema.ts");
		await writeFile(path, await bind(scripts));
		console.error(`${client}: ${Object.keys(scripts).length} scripts → ${path}`);
	});

// decisions — the agent-agnostic review surface, over createReviewer (read-only, no entity bridge).
// JSON on stdout so an agent reads each result; --agent picks whose Decisions table to read.
const decisions = program.command("decisions").description("Inspect an agent's Decisions (read-only).");

decisions
	.command("list")
	.description("List decisions — the pending queue by default — each flagged hasFeedback (any human edit) and overturned (the human changed the committed output).")
	.requiredOption("--agent <id>", "agent under agents/ whose config.ts names the Decisions table")
	.option("--reviewed", "only reviewed decisions (Final output set)")
	.option("--all", "both pending and reviewed")
	.option("--feedback", "only decisions carrying human feedback, each with the feedback itself — spans both states unless you narrow the scope")
	.action(async ({ agent, reviewed, all, feedback }: { agent: string; reviewed?: boolean; all?: boolean; feedback?: boolean }) => {
		const reviewer = createReviewer({ ...loadAgent(agent) });
		// Feedback lives in BOTH states — a Save carries a note with no Final output, a commit carries
		// an overturn — so asking for it means "wherever it is", not "in the pending queue". Hence the
		// default widens to `all`; an explicit --reviewed still narrows it.
		const scope = all || (feedback && !reviewed) ? "all" : reviewed ? "reviewed" : "pending";
		console.log(JSON.stringify(await reviewer.list(scope, { feedback }), null, 2));
	});

decisions
	.command("show")
	.argument("<decision>", "Decision id, Notion URL, or app URL")
	.description("One decision (judge's judgment + human diff), or with --feedback just the human feedback snapshot.")
	.requiredOption("--agent <id>", "agent under agents/ whose config.ts names the Decisions table")
	.option("--feedback", "print only the human feedback snapshot (LLM-oriented markdown)")
	.action(async (decision: string, { agent, feedback }: { agent: string; feedback?: boolean }) => {
		const reviewer = createReviewer({ ...loadAgent(agent) });
		const shown = await reviewer.showDecision(decision);
		if (feedback) return void console.log(shown.feedback ? renderFeedback(shown.feedback) : "(no human feedback)");
		// Was this judged under the instructions that are live now? The Decision pinned their
		// fingerprint; re-fingerprint the current body and say so. `stale` means someone edited a prompt
		// body in place (or the shared page it syncs) rather than adding a version — so this judgment
		// no longer stands on the criteria the prompt claims today. Unknown kind / pre-pin row ⇒ omitted.
		const live = shown.kind ? await reviewer.instructionsHash(shown.kind).catch(() => undefined) : undefined;
		const instructions =
			shown.instructions && live
				? { pinned: shown.instructions, live, stale: shown.instructions !== live }
				: { pinned: shown.instructions ?? null, live: live ?? null };
		console.log(JSON.stringify({ ...shown, instructions }, null, 2));
	});

// prompts — the live Prompt contracts, same reviewer, read-only. `list` indexes every declared
// kind (version + fingerprint — the `live` side of decisions show's staleness check); `show`
// prints one contract in full: the authored body, both schemas, and the hash a Decision made now
// would pin. Authoring stays in Notion's editor (prose is authored, not compiled).
const prompts = program.command("prompts").description("Inspect an agent's live Prompt contracts (read-only).");

prompts
	.command("list")
	.description("Every decision kind the agent declares → its live contract's version, fingerprint, and page.")
	.requiredOption("--agent <id>", "agent under agents/ whose config.ts declares the prompts")
	.action(async ({ agent }: { agent: string }) => {
		const reviewer = createReviewer({ ...loadAgent(agent) });
		console.log(JSON.stringify(await reviewer.prompts(), null, 2));
	});

prompts
	.command("show")
	.argument("<kind>", `prompt key in config.prompts (e.g. "qualify") or the Prompt's full Name`)
	.description("One kind's live contract in full: body (the authored instructions), Input/Output schemas, version, fingerprint.")
	.requiredOption("--agent <id>", "agent under agents/ whose config.ts declares the prompts")
	.action(async (kind: string, { agent }: { agent: string }) => {
		const { config } = loadAgent(agent);
		const reviewer = createReviewer({ ...loadAgent(agent) });
		console.log(JSON.stringify(await reviewer.showPrompt(config.prompts?.[kind]?.name ?? kind), null, 2));
	});

// docs — the Writer's long-form documents (the /write surface of the review app). No --agent: it is
// ONE shared writing table (NOTION_WRITER_DS), not an agent's model. `list` indexes them, `show` prints
// one with its body as markdown — the document itself, since prose lives in the page body — and `push`
// hands one back, live. Authoring stays in the app's editor (or Notion's); this is the loop between them.
const docs = program.command("docs").description("Read the Writer's documents, and push a revision into the open editor.");

docs
	.command("list")
	.description("Every document in the Writer's table — id, url, and its properties (Name, Status, …). Bodies are `show`'s job.")
	.action(async () => console.log(JSON.stringify(await writer.list(), null, 2)));

docs
	.command("show")
	.argument("<doc>", "document id, Notion URL, or app URL (/write/<id>)")
	.description("One document: its properties plus `markdown` — the page body, which IS the document.")
	.action(async (doc: string) => console.log(JSON.stringify(await writer.show(doc), null, 2)));

// push — the write, and the only one `sflock` has: a revision of a document, handed to the app's own
// save sink so it lands on the Notion page AND in the editor that has it open (no reload). Prose to a
// document; pipeline state stays the runtime binaries'. Markdown comes from a file or stdin, because a
// revision is text — not an argument.
docs
	.command("push")
	.argument("<doc>", "document id, Notion URL, or app URL (/write/<id>)")
	.argument("[file]", `markdown file; omit (or "-") to read the document from stdin`)
	.option("--title <title>", "also retitle the document (omit to leave its Name alone)")
	.description("Push a new version of a document: saved to Notion and applied live in the open editor (one undo step). Needs the local app running.")
	.action(async (doc: string, file: string | undefined, { title }: { title?: string }) => {
		const markdown = file && file !== "-" ? await readFile(file, "utf8") : await text(process.stdin);
		console.log(JSON.stringify(await writer.push(doc, { markdown, title }), null, 2));
	});

program.parseAsync().catch((e: unknown) => {
	console.error(renderError(e));
	process.exit(1);
});
