// Generated by `sflock bind` from *.scripts.ts. Do not edit — re-bind.

export interface Card {
  /**
   * The profile owner's name, and the response health check. Non-null means the top card parsed and the whole record is trustworthy. Null means the parse failed (auth wall, block, or blank render) — treat every other field as invalid rather than interpreting the nulls.
   */
  name: string | null;
  /**
   * Full About prose, line breaks preserved. Null means no About text was captured — either the profile has none, or (rarely) it did not load in time. Disambiguate with name: when name is non-null the top card parsed cleanly, so a null here almost always means the profile genuinely has no About section.
   */
  about?: string | null;
  /**
   * Connection degree badge as displayed (e.g. "1st", "2nd", "3rd"). Null on your own profile or when no badge is shown.
   */
  degree?: string | null;
  /**
   * Top-card headline line. Null when the profile has no headline.
   */
  headline?: string | null;
  /**
   * Top-card location as rendered. Null when the profile exposes no location.
   */
  location?: string | null;
  /**
   * Top-card follower count as an integer. Null when the card shows only connections.
   */
  followers?: number | null;
  /**
   * Stable internal member id (the tail of urn:li:fsd_profile:<id>, an ACoAA… token). Unlike publicId it never changes, so it is the join key for search_people's connectionOf. Read from the top-card Message button, so it is null whenever no Message button is shown — on your own profile, or on any profile you are not connected to (e.g. a distant 2nd/3rd-degree profile). A null here is not a parse failure; check name for that.
   */
  memberUrn?: string | null;
  /**
   * Canonical profile URL.
   */
  profileUrl: string;
  /**
   * Top-card connection count as rendered (e.g. "500+", "34"). Null when the card shows only followers.
   */
  connections?: string | null;
  /**
   * Top-card current-employer chip. Null when the card surfaces no company chip — the employer is then only in get_profile_experience.
   */
  currentCompany?: string | null;
}

export interface Experience {
  positions: {
    title: string | null;
    company: string | null;
    duration: string | null;
    location: string | null;
    dateRange: string | null;
    /**
     * LinkedIn /company/ or /school/ page; null when the org has no LinkedIn page
     */
    companyUrl: string | null;
    description: string | null;
    employmentType: string | null;
  }[];
}

export interface Posts {
  posts: {
    /**
     * urn:li:activity:<id>, from the card's data-urn.
     */
    urn: string;
    /**
     * Post commentary text; null when the post is media-only.
     */
    text?: string | null;
    /**
     * Display name of the entry's author (the original poster, or the repost source).
     */
    author?: string | null;
    /**
     * Permalink built from the urn.
     */
    postUrl: string;
    /**
     * Repost count as rendered; null when none.
     */
    reposts?: string | null;
    /**
     * Comment count as rendered; null when none.
     */
    comments?: string | null;
    /**
     * Author's headline/subtitle as rendered.
     */
    headline?: string | null;
    /**
     * Relative age, e.g. '2mo', '1w'; for a repost, when it was reposted, not the original time.
     */
    postedAgo?: string | null;
    /**
     * Reaction count as rendered, e.g. '27'; null when none.
     */
    reactions?: string | null;
    /**
     * Who reposted it into this profile's feed; null on an original (non-repost) entry.
     */
    repostedBy?: string | null;
    /**
     * True when the entry wraps quoted content (repost with thoughts).
     */
    isQuoteReshare: boolean;
  }[];
}

export interface Comments {
  comments: {
    /**
     * The post the comment was made on (from the comment's data-id, not the feed-wrapper card urn).
     */
    post: {
      url: string | null;
      /**
       * urn:li:activity:<postActivityId>.
       */
      urn: string | null;
      text?: string | null;
      author?: string | null;
      postedAgo?: string | null;
      authorHeadline?: string | null;
    };
    /**
     * The owner's comment text (full; null if the comment is media-only).
     */
    text?: string | null;
    /**
     * Relative age of the comment, e.g. '49m', '1d', '1w'.
     */
    postedAgo?: string | null;
    /**
     * Reaction count on the comment as rendered, e.g. '2'; null when none.
     */
    reactions?: string | null;
    /**
     * Comment identity: urn:li:comment:(activity:<postActivityId>,<commentId>).
     */
    commentUrn: string;
  }[];
}

export interface Company {
  name: string;
  phone?: string | null;
  logoUrl?: string | null;
  tagline?: string | null;
  /**
   * Inner numeric LinkedIn company ID from urn:li:fsd_company:N (e.g. 18834371 for almapay). Stable join key.
   */
  companyId: string;
  locations?: {
    city?: string | null;
    line1?: string | null;
    line2?: string | null;
    country?: string | null;
    postalCode?: string | null;
    isHeadquarter?: boolean;
    geographicArea?: string | null;
  }[];
  industries?: string[];
  /**
   * Company-declared website, returned verbatim — can be a linkedin.com self-link when the company set its own LinkedIn page as website (seen on stealth pages). Not normalized; filter linkedin.com values downstream if you need a real external site.
   */
  websiteUrl?: string | null;
  description?: string | null;
  foundedYear?: number | null;
  linkedinUrl?: string | null;
  headquarters?: {
    city?: string | null;
    line1?: string | null;
    line2?: string | null;
    country?: string | null;
    postalCode?: string | null;
    geographicArea?: string | null;
  } | null;
  specialities?: string[];
  /**
   * Count of LinkedIn members associated with the page, not the declared size — on catch-all/stealth pages it can wildly exceed employeeCountRange (battle-tested: 5,933 members on a page declaring 2-10). Use employeeCountRange for the company's self-declared size.
   */
  employeeCount?: number | null;
  followerCount?: number | null;
  /**
   * Canonical slug as LinkedIn returns it — may differ from the requested one if the page was renamed/redirected.
   */
  universalName: string;
  employeeCountRange?: {
    /**
     * null for open-ended ranges like 10K+
     */
    end?: number | null;
    start?: number | null;
  } | null;
}

export interface Feed {
  posts: {
    /**
     * The post's canonical urn as the site exposes it — urn:li:activity / urn:li:ugcPost / urn:li:share:<id> (sponsored posts are unwrapped to their inner urn:li:activity). Recovered from the control-menu overflow link href (Report post/ad, falling back to Embed this post). Null only when that menu link can't be read for the card (e.g. an unfilled slot).
     */
    urn?: string | null;
    /**
     * Full post commentary text (the '…more' clamp is visual only). Null for a media-only post with no commentary.
     */
    text: string | null;
    /**
     * Permalink built from urn: https://www.linkedin.com/feed/update/<urn>/ . Null when urn is null.
     */
    postUrl?: string | null;
    /**
     * From the repost button's own count; absence reads as 0.
     */
    reposts: number;
    /**
     * From the comment button's own count; absence reads as 0.
     */
    comments: number;
    /**
     * Author's subtitle as rendered (role/bio for a person, follower count for a company page).
     */
    headline?: string | null;
    /**
     * True when a connection reposted this into the feed (their name is in repostedBy).
     */
    isRepost: boolean;
    /**
     * Relative age, e.g. '2d', '6d', '19h'. Null for sponsored posts, which show 'Promoted' instead.
     */
    postedAgo?: string | null;
    /**
     * From the reaction button's own count; LinkedIn omits zero counts in the UI, so absence reads as 0.
     */
    reactions: number;
    /**
     * Display name of the post's author (person or company/organization page).
     */
    authorName: string | null;
    /**
     * Who reposted it into the feed; null unless isRepost is true.
     */
    repostedBy?: string | null;
    /**
     * True for ads / promoted posts (including creator brand partnerships, 'Promoted by X').
     */
    isSponsored: boolean;
    /**
     * /in/<id> for a person or /company/<slug>/posts/ for an organization.
     */
    authorProfileUrl?: string | null;
    /**
     * As rendered: '1st'/'2nd'/'3rd+', or 'Following' when already following instead of connected; null for company/organization authors.
     */
    connectionDegree?: string | null;
  }[];
}
